# PostgreSQL Database Configuration

spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate Configuration

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true


# Spring Security Configuration

jwt.expiration=${JWT_EXPIRATION:900000}
jwt.key=${JWT_KEY:QxLcogD4gVCKsDwbTCEEwCjvsSqNxVwQrp3saiq5hffJ5VwdXFG9470vLIVG4oHB3VSFAY0te5r694kvS8oJbIhBzX_OjM90peYjSUeUucloqg1wQ5e&tTRF}


# OpenAPI / Swagger Configuration

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html